# Generated by Django 6.0.1 on 2026-03-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dept_head', 'Department Head'), ('project_lead', 'Project Lead'), ('collaboration', 'Collaboration')], default='collaboration', max_length=20),
        ),
    ]
