# Generated by Django 6.0.1 on 2026-03-28 17:18

from django.db import migrations


def update_member_to_collaboration(apps, schema_editor):
    """Update all users with role 'member' to 'collaboration'"""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='member').update(role='collaboration')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(update_member_to_collaboration, reverse_code=migrations.RunPython.noop),
    ]
