# Generated by Django 6.0.1 on 2026-03-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_remove_department_name_department_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='workspace_code',
            field=models.CharField(default='TEMP', max_length=20, unique=True),
        ),
    ]
